---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sarthak-prime-app
  labels:
    app: sarthak-prime-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sarthak-prime-app
  template:
    metadata:
      labels:
        app: sarthak-prime-app
    spec:
      containers:
      - name: sarthak-prime-container
        image: 980921713953.dkr.ecr.us-east-1.amazonaws.com/amazon-prime:latest
        ports:
        - containerPort: 3000
...
